author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''



#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '56112100605'
      #password 密码
      password: '20243997k7kfpf'
      #address 地址，定位信息
      address: '浙江省杭州市滨江区'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 浙江商业职业技术学院
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 120.169708
      #lat 纬度
      lat: 30.180426
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 身体健康与否
            value: 健康
        - form:
            title: 从今天算起前14天内是否到过中高风险地区
            value: 否
        - form:
            title: 从昨天打卡到现在是否有接触过疑似或确诊的新冠肺炎患者
            value: 否
        - form:
            title: 今日杭州健康码颜色
            value: 绿色
 
